### ISSUE TITLE
Feature request: Different landing page when user is not logged in.

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#100]

**Comment by philippejadin** [comment]
what would be the content of this page?

**Comment by msjmeyer** [comment]
Give the admin of the site to update the content of the site as he wishes. 
Same as what you have on the homepage currently with the "Change intro text"

**Comment by philippejadin** [comment]
Do you mean, different intro text for non logged and logged in users?

**Comment by philippejadin** [comment]
The new admin settings page (work in progress) will soon address this
