### ISSUE TITLE
Feature request: help page

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#101]
Creating a page where the admin can add help content, possible location can be when clicking on your username the menu.

**Comment by philippejadin** [comment]
Great idea. I'd like to provide a default help page ideally. If you have good wordings let me know

**Comment by msjmeyer** [comment]
Ill look for a template to copy.

**Comment by philippejadin** [comment]
Needed for hart boven hard "Privacy and disclaimer" page

**Comment by philippejadin** [comment]
there is now one. It can be edited by admin in settings
