### ISSUE TITLE
Users on the overview tab

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#102]
To clean up the users on the overview tab as well the member on the home page can be removed as search does find users. Alternatively users can find others by searching as well as being in same group as them. 

Personally feels like it clutters up the UI, thoughts?

**Comment by philippejadin** [comment]
Same as #103, I'd put those in a "more..." tab

**Comment by msjmeyer** [comment]
One thing to be careful of not a lot of sites have these member lists anymore since users can easily spam people then.

**Comment by philippejadin** [comment]
closing as it depends on the new ui I'm working on
