### ISSUE TITLE
Files on the Overview.

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#103]
To clean up the UI we can remove files from the overview menu as well as the homepage.
Files are a lot more helpful when it's in a group as recources and maybe even the help page.

Thoughts on this?

**Comment by msjmeyer** [comment]
Question, if a group is private is the files then private and hidden from searching as well?

A simple solution can on the files tab for groups to have a "show all" files button.

**Comment by philippejadin** [comment]
Yes private items won't be shown to users not members of the private group. I'd prefer not provide a show all on a group, since it might confuse the users.

**Comment by msjmeyer** [comment]
ok, so for the files tab in the home page what does it not do if not showing all recent files?
Yeah i can see how that can be confusing, hmm need to think about it.

**Comment by philippejadin** [comment]
closing as it depends on the new ui I'm working on
