### ISSUE TITLE
PHP 7.1 Fatal error in Illuminate/Foundation/Exceptions/Handler.php

### ISSUE THREAD

**Issue by VMFnet** [philippejadin/agorakit#108]
Hello, i just updated my installation [with steps outlined here](https://github.com/philippejadin/agorakit/wiki/Updating-an-existing-installation), and now i get this error : 

PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:96

Stack trace:
#0 [internal function]: Illuminate\\Foundation\\Exceptions\\Handler->Illuminate\\Foundation\\Exceptions\\{closure}(0, 'Illuminate\\\\Auth...')
#1 /var/www/bootstrap/cache/compiled.php(6449): call_user_func(Object(Closure), 0, 'Illuminate\\\\Auth...')
#2 /var/www/bootstrap/cache/compiled.php(12660): Illuminate\\Support\\Arr::first(Array, Object(Closure), NULL)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(97): Illuminate\\Support\\Collection->first(Object(Closure))
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(61): Illuminate\\Foundation\\Exceptions\\Handler->shouldntReport(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#5 in /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 96

**Comment by philippejadin** [comment]
Please try to remove bootstrap/cache/compiled.php and see if that helps. It's a laravel 5.4 upgrade issue most probably

**Comment by VMFnet** [comment]
Indeed, this solved the problem.  Thanks !

**Comment by philippejadin** [comment]
Great. I mentionned this in the 0.5 release notes : https://github.com/philippejadin/agorakit/releases/tag/v0.5

**Comment by VMFnet** [comment]
Sorry, didn't read that before upgrading.  Will RTFM next time ;-)

**Comment by philippejadin** [comment]
Quite the contrary, it's because you opened this issue that I added the details, so thank you :-)
