### ISSUE TITLE
New ui mockup, please comment

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/agorakit#109]
Here you have a mockup of a new UI I'm thinking of implementing : 
https://github.com/philippejadin/agorakit/blob/dev/docs/dev/agorakit_new_ui.svg.png

- merge home page "overview" and group home page
- provide a big dropdown menu to select either : one of my group / my groups / all groups
- menu is always the same : Discussion / Agenda / Files / Members

Much simplier and consistent imho, but I'd like to have feedback.

This will happen in the dev branch, I advise anyone to use the 0.5 release in prod for now.

@msjmeyer @slester @goofy-bz @BreoganGal @danielsum feedback welcome :-)

**Comment by msjmeyer** [comment]
Im pulling it into my dev today, will let you know :)

**Comment by BreoganGal** [comment]
We started using it this coming month;)

2017-10-25 15:45 GMT+02:00 msjmeyer <notifications@github.com>:

**Comment by BreoganGal** [comment]
Good afternoon, on Agorakit, it could be interesting to add a task section
(as if it were a discussion), assign it to a person and when they are
complete mark them as completed.

2017-10-28 19:31 GMT+02:00 Noel Rodríguez <noelrf.ou@gmail.com>:

**Comment by philippejadin** [comment]
@BreoganGal let's discuss the task management in another issue. (and btw I'd be interested in the url of your install, just out of curiosity :-))

@everyone, I tried implementing the feature in new_filter_ui branch, but it din't work well on the tech side, so I'm closing this down for now, might be interesting to reopen it later. 

I think I need UX help before trying any new experiment in code :-)
