### ISSUE TITLE
Check out human-connection.org

### ISSUE THREAD

**Issue by frankgerhardt** [philippejadin/agorakit#112]
Looks like similar goals and tech stack. Join forces?

**Comment by philippejadin** [comment]
Nice!
I didn't find the source code, where is it ?

**Comment by frankgerhardt** [comment]
it is open-source on BitBucket somewhere. They have an onboarding process where one has to sign a data privacy statement. In the future they want to be more open and move to github or gitlab.

**Comment by philippejadin** [comment]
I'll keep it on my radar, thank you
