### ISSUE TITLE
Permettre de répondre @quelqu'un dans les commentaires

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/agorakit#12]
il faut réfléchir à l'implantation

**Comment by danielsum** [comment]
On peut utiliser ça : https://github.com/DraperStudio/Laravel-Mentions avec ce script là : http://ichord.github.io/At.js/ ?

**Comment by philippejadin** [comment]
Cool!
On peut même mettre dans les "friends" les membres du groupe dans lequel on est actuellement pour augmenter leur priorité?

Puis un handler qui envoi un mail à la personne mentionnée (seulement lors du premier save)
