### ISSUE TITLE
upload Photo size 

### ISSUE THREAD

**Issue by ElectroArmy** [philippejadin/agorakit#172]
hello i need to upload  high resolution photos in group.

Please.. sir

**Comment by ElectroArmy** [comment]
I also upload PDF to files... and i got error like this .....
![fileuploaderr](https://user-images.githubusercontent.com/39894962/43061565-c5989c48-8e7b-11e8-8906-f2a0a438e486.PNG)

**Comment by philippejadin** [comment]
Photos are currently resized and this is not configurable. What would you
like exactly? This could be added in a future version

On Monday, July 23, 2018, ElectroArmy <notifications@github.com> wrote:
> hello i need to upload high resolution photos in group.
>
> Please.. sir
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/OkrQm6K_1n8Rn2hj3s-qxbVW8S66ZL8VNU61EdeiWEdNLGmh4JaUq8y6vXWXsuwiOAcNVnp5Np3xVNDcqtK03brFzTFk7D31Tro4dJ0H_Fb33Ia_Wwf0VQnLLbiAqmkcikA7GPudnrJc6fl7jUOwg4FM8aRXXQ=s0-d-e1-ft#https://github.com/notifications/beacon/ABJM9ZCvbzHmitVMXgJp4JNLdlIR3QdUks5uJWXugaJpZM4VaZ6l.gif
>

-- 

Philippe Jadin

**Comment by philippejadin** [comment]
This is a permission problem on your server. Please check laravel install
guide for your plateform

On Monday, July 23, 2018, ElectroArmy <notifications@github.com> wrote:
> I also upload PDF to files... and i got error like this .....
> <
https://ci4.googleusercontent.com/proxy/OHCeaNW0bmNDT3o6XOqtNac5k8aix_rP8rOvqU0wTWKuUPVdH6L1v4x-xp1aJ9ZkYtblnnaVB9YDBLS1PDzjb7IvBRADYwTF5MiHVMLH-DDfVhSoaPFf9BQNSSzKITu-QhlqXwgQhUYLdkMEfXY4IdzsYTPvSQSkovY=s0-d-e1-ft#https://user-images.githubusercontent.com/39894962/43061565-c5989c48-8e7b-11e8-8906-f2a0a438e486.PNG
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/rzkGAt9FdMn_50QOKmZy7aqd-ICyBKbAYtQzgGpp6F-Ts8W8h-kV-FmqRW9PYbqgLB81NBu74RiRufHRhMW2jl8id78rkNZCGdsxGJLvFdAVraap-U20GNQDUb_vTSWTLEd7h00u4N3hYXPkiub1w_Ug6DajUA=s0-d-e1-ft#https://github.com/notifications/beacon/ABJM9Rsb8L6gYNVn5Xo6mPGxqzx4_67Xks5uJXNDgaJpZM4VaZ6l.gif
>

-- 

Philippe Jadin

**Comment by ElectroArmy** [comment]
thanks :)
