### ISSUE TITLE
Route +need help

### ISSUE THREAD

**Issue by ElectroArmy** [philippejadin/agorakit#173]
hello. i've already existing project. 

I want to Route agorakit to like /group.
Now its all are route to index. !
Could u please tell me?

thanks

**Comment by philippejadin** [comment]
You could probably change the rewrite rules. Check the file called .ht
access and read about apache rewrite rules. It's not easy stuff
unfortunately 🤔

On Monday, July 23, 2018, ElectroArmy <notifications@github.com> wrote:
> hello. i've already existing project.
>
> I want to Route agorakit to like /group.
> Now its all are route to index. !
> Could u please tell me?
>
> thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/U9reJ9ZKtER6ULfx_GOQaIvPaNfDtatiCHO62KqkALqXmeLSLrDzSSDcT7HPc4YWppn1E4ICFwwenTTU1p-51p0_sn7U8PR1RslTxtN-elcZSqUhlCrORCmdXEpbD5aofKllL7XdkMt_8T7xYAILS1Merjm5mA=s0-d-e1-ft#https://github.com/notifications/beacon/ABJM9TxF9rlMXNbdOEzJpnmv3Kdb49VUks5uJZnugaJpZM4VarQA.gif
>

-- 

Philippe Jadin

**Comment by ElectroArmy** [comment]
yep... i changed to Route:: web.php and going works fine :) thanks
