### ISSUE TITLE
Group deletion not working on app.agorakit.org

### ISSUE THREAD

**Issue by nedjo** [philippejadin/agorakit#177]
On https://app.agorakit.org, group deletion is not working.

Steps to reproduce:

* Register and create a group.
* Navigate to the "delete" option for the group, such as https://app.agorakit.org/groups/141/delete.
* Result: exception and the message "Whoops, looks like something went wrong."

Haven't tested on a local install.

**Comment by philippejadin** [comment]
thank you for the report. Actually group deletion by group admins has been disabled for now (and not removed from the UI...), only "super" admin (site-wide) can delete groups. What do you think about this behaviour?

**Comment by nedjo** [comment]
> only "super" admin (site-wide) can delete groups. What do you think about this behaviour?

Makes sense. It sounds like this is introducing a user role access issue. Ideally, perhaps, there would be a role-based permission that determined access, with the UI element being dependent on that permission.
