### ISSUE TITLE
Allow user to delete own account

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/agorakit#179]
Battle plan : 

- [x]  create a system user (whose email might be anonymous@agorakit.org for instance) -> simple migration
- [x] add a button to allow user to delete account
- [x] let user choose between delete account and content or delete account and assign content to anonymous user
- [x] depending on choice, either delete all or change user on all content
- [x] profit!

- [x] Bonus : add the same feature for admins (in case of spam)

**Comment by philippejadin** [comment]
this has been merged into master

**Comment by nedjo** [comment]
Nice work, thanks!
