### ISSUE TITLE
Use event subscriber for notification on mention

### ISSUE THREAD

**Issue by nedjo** [philippejadin/agorakit#186]
In `MentionUsers::create()`, we parse posted text for mentions and send out notifications.

This works, but means any logic related to the response needs to go into the the `MentionUsers` code. In #183 we're considering altering the notification logic, adding complexity.

So this might be a case for using the event subscription pattern. By dispatching an event, we can leave `MentionUsers` free of code related to mention responses. This would also facilitate adding different responses to mentions. For example, we might provide users the ability to browse past events for their user, including mentions.

**Comment by philippejadin** [comment]
I'm  not sure I see the advantage here. Do you mean something like that : https://laravel.com/docs/5.7/eloquent#observers

I made a trait for the mentions, but I agree in retrospect it's a bit strange since it's tied to a specific model (comments) currently. Need to think about it more

**Comment by nedjo** [comment]
> Eloquent models already dispatches several events, might probably good to hook on comment::created (to notify users only once)

That sounds good, but I think we'll still need a custom mention event. Mentions may be supported outside of comments--say, in initial discussion posts, or in some component we add in the future. So, maybe, the comment observer uses the current trait, which parses the text for mentions and dispatches a mention event for each mention found. The listener is about sending the notification.

**Comment by philippejadin** [comment]
Here is the current state of affairs : https://github.com/philippejadin/agorakit/tree/better-mentions

I think I found a reasonable solution : 
- CommentController emits a "ContentCreated" event (leaving room for another controller to emit the same event for another type of content)
- A listener called NotifyMentionnedUsers reacts on this event and send the required notifications

The logic involved in sending the notification depend on the content type so it seems the right architecture and at least I got to know the event system a bit more.

I also simplified the mentions, they now use a newly introduced "username" (which cannot contain spaces)

Feedback appreciated!

**Comment by philippejadin** [comment]
This seems closed and works fine now, so closing it. For memory, there is still a need to allow mention elsewhere (for example in discussions initial body, but it can wait)
