### ISSUE TITLE
bug while installing agorakit on 1and1, again

### ISSUE THREAD

**Issue by gilluc** [philippejadin/agorakit#202]
thanks for the solution, i will add the famous line:
Schema::defaultStringLength(191);
even if i cannot understand what is 191 ....

then i had to run again the "migrate" process that stopped in the middle...
I hope this process was written and tested so good that it will run without error a second time ? 
gilles

**Comment by philippejadin** [comment]
yes try to run it again and check the return. Since this bug first appeared, it's most probably related to an outdated version of mysql at your hosting provider.

As far as I understand, 191 is a default value and could have been something else

Note that you don't need to update files manually, just run "git pull" in your folder install to update to the latest release

**Comment by gilluc** [comment]
MySQL 5.5 ...

**Comment by philippejadin** [comment]
they are at 8.0.12 :-)

**Comment by gilluc** [comment]
again ... error ...
i think some cleaning must be done before running migrate a seconf time...
###!!!!$$$$$???
is it enough to drop all tables in phpmyadmin ???

(uiserver):u39028535:~/agorakit$ /usr/bin/php7.1-cli artisan migrate
Migrating: 2017_08_19_175307_create_social_profiles

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'social_profiles' already exists (SQL: create table `social_profiles` (`id` int unsigned not null auto_increment primary key, `user_id` int unsigned not null, `provider` varchar(191) not null, `provider_id` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')

  at /homepages/40/d141356676/htdocs/agorakit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'social_profiles' already exists")
      /homepages/40/d141356676/htdocs/agorakit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      /homepages/40/d141356676/htdocs/agorakit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  Please use the argument -v to see more details.
(uiserver):u39028535:~/agorakit$

**Comment by gilluc** [comment]
oops : git pull worked succesfully before migrate
i think.

**Comment by gilluc** [comment]
i decided to drop all table and run artisan migrate
the same error "key too long" 
the laravel fix with git  pull doesnt work at all

i try modifying file AppServiceProvider.php to 1024 default
and drop tables and rerun artisan migrate

unfortunately, i decide to download the folder of agorakit...to find and modify AppServiceProvider.php
....
after 12.843 files and 1.718 directories for 221 MB, filezilla decided to stop...
but AppServiceProvider.php was here and i modified it then uploaded it back.
...
then putty said that my SSH connection did not work anymore so running artisan migrate is delayed again...

putty is ok now ... retry to run artisan migrate ...

SAME ERROR AGAIN (EVEN AFTER MODIFYING DEFAULT LENGTH TO 1024 in AppServiceProvider.php
but now directly on the first table in the migration...

 Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")
      /homepages/40/d141356676/htdocs/agorakit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      /homepages/40/d141356676/htdocs/agorakit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

**Comment by gilluc** [comment]
i give up !!!
