### ISSUE TITLE
Usability: Admins may accidentally delete group

### ISSUE THREAD

**Issue by nedjo** [philippejadin/agorakit#203]
It is easy to accidentally delete a group. This recently occurred with a group on https://app.agorakit.org via the following steps:

* User with administrator role for a group views a given item within that group's context, such as an event.
* User wishes to delete the item and sees a menu "Administration", which seems relevant. Selects the option "delete". However, what is deleted is not the discussion but the entire group.

Possible approaches to resolve (not all mutually exclusive):

* Don't provide a drop-down menu on Administration. These are little-used options and probably don't need a shortcut.
* Don't provide a drop-down link to delete. This is a seldom needed step that should be relatively hard to complete.
* Make it clear through labelling that "Administration" applies to the group.
    * Change "Administration" to "Administer group".
    * Under Administration menu, change "Edit" to "Edit group" and "delete" to "Delete group".
* Improve warnings given prior to deleting group.

**Comment by philippejadin** [comment]
Thanks for the report, will add it to the todo. By the way there is a near perfect undelete feature if needed (but only for superadmin, so mail me if an undelete is needed :-))
