### ISSUE TITLE
Create a new dicussion without a group small bug

### ISSUE THREAD

**Issue by Kayoku** [philippejadin/agorakit#206]
Hi,

If you try to create a new discussion without specify a group, you finish into an error page with this message:

"Sorry, the page you are looking for could not be found.
No query results for model [App\Group]."

Maybe,, it would be good to make the field "required" or something like that ? (as the title field)

**Comment by Kayoku** [comment]
Yeah sure. I'm just starting with your tool so PR will probably come later... Time to understand how all this nice stuff works :)

**Comment by philippejadin** [comment]
Basically it follows the laravel way of working. Nice introduction series about laravel : https://laracasts.com/series/laravel-from-scratch-2018 

When you know laravel, you know agorakit, and when you know laravel a whole world opens to you in terms of quite clean code :-)
