### ISSUE TITLE
"asset" to "secure_asset"

### ISSUE THREAD

**Issue by Kayoku** [philippejadin/agorakit#207]
Hi,

I was trying to make AgoraKit works with HTTPS and found some fail that make my page "unsecure" :(
The easy solution is to replace every "asset" by "secure_asset" (https://laravel.com/docs/5.7/helpers#method-asset) to force Laravel to create url with HTTPS.

Do you agree ? Don't you have any issue cause of "asset" ? Maybe it's a nginx problem in my setup. But I think that everyone use HTTPS nowadays (and if not, you should !)

If you agree, I'll propose a PR soon.

**Comment by Kayoku** [comment]
In the same way, maybe it can be useful to force HTTPS in production by adding this to the boot method of the AppServiceProvider 

```
if (config('app.env') === 'production') {
 $this->app['request']->server->set('HTTPS', true);
}
```

**Comment by philippejadin** [comment]
Fine, PR welcome!  I run all installs with https but it's on apache so maybe it's related to nginx.
