### ISSUE TITLE
User can't change own email on profile edit screen

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/agorakit#214]

**Comment by chzplz21** [comment]
I just tried to change my email and it worked. Can't seem to replicate the issue.

**Comment by philippejadin** [comment]
I'll ask for more info from the reporter. We'll close the issue if no feedback received. Thanks for trying to replicate

**Comment by chzplz21** [comment]
For Sure, Thanks.

**Comment by philippejadin** [comment]
can't reproduce either. Closing
