### ISSUE TITLE
accept email or username on login page

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/agorakit#215]
Not hard to do and really useful I think.

Need to triple check security issues

**Comment by James-N-M** [comment]
Just wondering if this is still up for grabs id like to get involved

**Comment by philippejadin** [comment]
It sure is ! And welcome to the project by the way :-)

If you need any additional informations don't hesitate. 

I found this tutorial that might be useful for you : https://tutsforweb.com/laravel-auth-login-email-username-one-field/

**Comment by James-N-M** [comment]
@philippejadin I was having some trouble setting up my development environment, I'm on mac using valet. My php storm let me know of the existence of a docker image, I dont know docker but im wondering if I figured out how to use docker if that would make the development environment set up a piece of a cake ? I was having trouble with mysql things my local version being 8 so the new auth stuffs giving me some trouble

**Comment by philippejadin** [comment]
There is the option of using vagrant : https://agorakit.readthedocs.io/en/latest/development.html
But I'm not sure the vagrant file is working, maybe @danielsum can help us :-)

**Comment by philippejadin** [comment]
I re-added vagrant but I have no experience with it.

**Comment by James-N-M** [comment]
@philippejadin whats your dev environment use ? I do have a ton of experience using vagrant so its not an issue

**Comment by philippejadin** [comment]
I'm on linux and I install everything I need (like php 7, apache, mysql and php modules) then I just run `php artisan serve` to start a local webserver. It's imho simplier than vagrant, but you need to install everything by hand and ideally be on linux. 

Having a simplier workflow for new devs would be awesome, so any help is welcome

**Comment by James-N-M** [comment]
@philippejadin I'm assuming your mysql version is below 8 ? I think thats the source of my problems when trying to get this going last week. I'm gonna reach out to some friends and document the process when i hopefully get it working :)

**Comment by philippejadin** [comment]
well I run a much older one on my laptop and didn't follow the evolution of mysql. Maybe it's related to this : https://ma.ttias.be/mysql-8-laravel-the-server-requested-authentication-method-unknown-to-the-client/ ?

This cries for a new issue, I'll create it and assign it to you if you don't mind :-)

**Comment by James-N-M** [comment]
@philippejadin do I need create a fork of the project to create a branch ?? 
`git push --set-upstream origin accept-email-or-username-login
remote: Permission to philippejadin/agorakit.git denied to James-N-M.
fatal: unable to access 'https://github.com/philippejadin/agorakit.git/': The requested URL returned err`

**Comment by James-N-M** [comment]
going to fork it anyways just cause

**Comment by James-N-M** [comment]
I dont seem to be able to be able to get this working, I had it working randomly, then I changed my 
```CREATE USER 'ohdear_ci'@'localhost' IDENTIFIED WITH mysql_native_password BY 'ohdear_secret';``` 
So I could run php artisan migrate and now I'm getting gateway time-outs 😪

**Comment by James-N-M** [comment]
It seems the app will open when using a mysql user, with mysql 8 auth whatever it is, but to use migration things i need to use a older auth solved by that post you shared..... Strange I guess ill just have to jump back and forth lol

**Comment by philippejadin** [comment]
closed by #240

**Comment by philippejadin** [comment]
Thanks to @James-N-M

**Comment by James-N-M** [comment]
@philippejadin if theirs another simple issue I can do let me know. I still wanna play around with the application, also I noticed the /docs folder, is there a way to read it in the browser ?

**Comment by philippejadin** [comment]
I try to label "simple/first" issues, currently there is one : https://github.com/philippejadin/agorakit/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

You can read the docs here : https://agorakit.readthedocs.io/en/latest/

And you can contribute to the docs as well since this department is lacking :-)
