### ISSUE TITLE
Unable to visit group when logged in

### ISSUE THREAD

**Issue by vince2bir** [philippejadin/agorakit#255]
I'm not able to access https://app.agorakit.org/groups/39 when I'm logged in. If I have logged out, I can visit the group page.

The error message is
`A fatal error occured
Trying to get property 'exists' of non-object (View: /home/agorakit/www/agorakit/app/resources/views/groups/show.blade.php) `

**Comment by philippejadin** [comment]
thank you, this has been solved just now.
