### ISSUE TITLE
Issue with ical synch on thunderbird

### ISSUE THREAD

**Issue by quentin-abiterra** [philippejadin/agorakit#256]
Hi,
I wanted to sync my Thunderbird (60) (with lightning extension 6.2.5) to the Agenda of my group throw the ical link but it seems to sync all agendas from all agorakit groups.

As informations are private, i don't publish screenshot but the procedure is quite simple:
- copy link from 
![image](https://user-images.githubusercontent.com/49190209/64610225-170e1280-d3cf-11e9-8779-570b441428eb.png)
- add a new agenda from server with ical link
and sync it.
![image](https://user-images.githubusercontent.com/49190209/64610290-36a53b00-d3cf-11e9-9c75-5cf560e222af.png)

https://app.agorakit.org/groups/NUMBER/action/ical

I haven't find any similar issues on the Github, as i'm not used to this app, maybe I missed something.

thanks for the quite simple and usefull app.

**Comment by philippejadin** [comment]
I will check this asap. There is a good chance that only information from
public groups are shown but it's still not what the users need.

Thank you for reporting!
--
Philippe Jadin

**Comment by philippejadin** [comment]
The latest commit should solve all issues. Really big thank for reporting this big privacy issue. Will add some automated tests to avoid this in the future.

**Comment by quentin-abiterra** [comment]
Thanks for the quick reaction.

**Comment by philippejadin** [comment]
Well that was really needed :-/
