### ISSUE TITLE
Error while following the installation process: PHP_VERSION not set

### ISSUE THREAD

**Issue by vpoulailleau** [philippejadin/agorakit#257]
I'm trying to install agorakit which looks great. I'm using (the excellent) alwaysdata hosting.

According to https://agorakit.readthedocs.io/en/latest/installation.html, I do `composer install`, I get an error message:

```
~/agorakit$ composer install
Variable PHP_VERSION not found
```

I assume that I have to set PHP_VERSION environment variable to 7.2.3 or something similar. I'll try, but I think this could be added to the documentation.

BTW, thanks for all your work.

**Comment by vpoulailleau** [comment]
Well, that's not sufficient.

```bash
~/agorakit$ export PHP_VERSION=7.2.22
~/agorakit$ composer install

Fatal error: Uncaught Error: Class 'Phar' not found in /usr/share/composer/composer.phar:23
Stack trace:
#0 {main}
  thrown in /usr/share/composer/composer.phar on line 23
```

**Comment by philippejadin** [comment]
Could you ask alwaysdata directly? I never had this issue. Their support is excellent. If you get some information that imply some changes on agorakit, please report back here.

**Comment by vpoulailleau** [comment]
Oops, I forgot this issue. The problem comes from alwaysdata: they had planned tasks that were not yet done. I now can execute the installer, which fails because I tried on a free account (100 MB of HDD), but agorakit dependencies use a lot more than that (currently, with a partial installation, dependencies use 170 MB). I ran out of disk space. I have to find another solution…
