### ISSUE TITLE
Affichage logo/favicon

### ISSUE THREAD

**Issue by PierreLecomte** [philippejadin/agorakit#268]
Bonjour,
On vient de m'installer une instance d'agorakit, qui a l'air de très bien marcher ce qui est réjouissant. 

Par contre, il y a un bug que je ne comprends pas :
Depuis l'espace admin, dans les settings j'ai voulu importer un logo/favicon...
Je vois qu'un dossier est bien créé dans html/storage/app/public/logo avec les deux images.
Mais le favicon ne s'affiche pas sur le site. L'adresse du favicon affiché dans la page (et qui ne s'affiche donc pas) est https://vallees-citoyennes.fr/storage/logo/favicon.png

Par ailleurs, même en créant un dossier html/storage/logo et en y mettant les 2 images créées lors de l'import dans html/storage/app/public/logo, l'image ne s'affiche toujours pas.

Je ne comprends donc pas... mais ça doit être très simple donc j'espère que vous saurez m'expliquer.
Merci !

**Comment by philippejadin** [comment]
Ah, je me demande si il ne faut pas faire

php artisan storage:link

ce qui n'est pas expliqué dans les docs, je vais l'ajouter

Dites moi si ça fonctionne comme ça

--
Philippe Jadin

**Comment by PierreLecomte** [comment]
Oui ça marche maintenant !
Merci de votre réponse rapide !

**Comment by manu-p** [comment]
Bonjour, désolé de rouvrir ce sujet, mais j'obtiens bien un favicon mais pas le logo en haut à droite en lieu et place de celui d'agorakit.

L'analyse du code HTML indique que ce logo est dans https://.../storage/logo/favicon.png (en 40x40) mais le seul favicon.png que je trouve est dans ./storage/app/public/logo/favicon.png

Je serais preneur des précisions nécessaire pour faire afficher ce logo... :-)

**Comment by philippejadin** [comment]
il faut faire php artisan storage:link pour linker le dossier public
et puis tu peux en uploader dans dans admin > settings

**Comment by manu-p** [comment]
Oui, j'ai bien téléversé un logo via les settings d'admin. Et j'ai aussi passé la commande `php artisan storage:link` également, qui m'a affiché : 
```
The [/var/www/agorakit/public/storage] link already exists.
The links have been created.
```
Seul le favicon de l'onglet (firefox) est pris en compte, pas le logo en haut à gauche du nom de l'application (agorakit initialement).

**Comment by philippejadin** [comment]
ici ça marche... Pas de problème de permission sur le dosser de stockage? que se passe-t-il si tu affiche l'image, il donne quelle url? php image installé ?

**Comment by manu-p** [comment]
Correct! Merci encore @philippejadin.

Pour être précis, après l'installation sur un dossier utilisateur, j'ai déplacé le tout sur /var/www/agora, qui me convient mieux pour les sites web, mais les liens symboliques qui sont définis de manière absolue (et non relative à la racine d'agorakit) ne sont plus bons, on s'en doute. Et par conséquent, le lien symbolique de public/storage pointait sur un dossier qui n'existe plus...

Apparemment, il n'y a qu'un lien symbolique, celui-là.

**Comment by philippejadin** [comment]
au moins ça permet de vérifier que ce n'est pas un bug d'agorakit :-)
c'est fou comme il y a bcp d'endroits ou ça peut foirer l'installation.

--
Philippe Jadin
https://123piano.com
https://fablabke.be
https://agorakit.org
