### ISSUE TITLE
Notifications non envoyées

### ISSUE THREAD

**Issue by PierreLecomte** [philippejadin/agorakit#273]
Bonjour,

Agorakit envoie bien des mails pour :
- confirmer une inscription
- transmettre un message d'un membre

Par contre, on ne reçoit aucune notification quotidienne, hebdomadaire etc. de nouveaux messages postés.
Pourtant, on a exécuté un php artisan schedule:run

**Comment by philippejadin** [comment]
regardez dans les logs du framework - je n'ai jamais eu de rapport dans ce sens
