### ISSUE TITLE
Accès limité à Agorakit

### ISSUE THREAD

**Issue by Julie-Kesteloot** [philippejadin/agorakit#275]
Bonjour Philippe,

Avec mon adresse mail julie.kesteloot@fdss, je peux avoir accès aux principaux contenus de mes groupes (Ecole de Transformation sociale)  mais je ne peux pas :
- télécharger de fichier (autrement qu’en attachant une pièce jointe à un fil de discussion) 
- créer un évènement dans l’agenda
- visualiser la liste des participants
- Créer une nouveau fil de discussion
-….

Chaque fois je tombe sur cette mention :
Votre adresse mail n'est pas vérifiée, merci de la vérifier maintenant depuis votre boite email 
Si vous n'avez pas reçu le mail de confirmation cliquez ici pour en recevoir un autre 
Votre adresse mail n'est pas vérifiée, merci de la vérifier maintenant depuis votre boite email 
Accueil
Hi,
Agorakit main developer speaking. I'm glad you are using the tool. If you have ideas of improvements and/or feedback, please join this group and let's talk there! 
•	A bug in the notification system stoped emails in the last few days. The problem has been fixed. Sorry for the inconvenience.
•	"Post by email" is still a work in progress, consider it as a beta feature.
Bonjour,
Ici le développeur principal d'Agorakit. Je suis ravi que vous utilisiez cet outil. Si vous avez des idées d'améliorations et/ou des retours, merci de rejoindre le groupe prévu pour et discutons-en là bas! Notez que la fonctionnalité "poster par email" est en développement.
Philippe

Et bien entendu, je clique sur le lien pour vérifier mon adresse mail, mais je ne retrouve pas de mail de confirmation (y compris dans les spams)

Merci pour votre aide !

Julie

**Comment by philippejadin** [comment]
j'avalidé manuellement votre adresse
