### ISSUE TITLE
Problème de compte

### ISSUE THREAD

**Issue by Aureliensausy** [philippejadin/agorakit#276]
Bonjour,

Ayant rencontré des problèmes avec la gestion du compte j'ai décidé de supprimer mon compte pour en créer un nouveau. Sauf qu'au moment de créer un nouveau compte avec la même adresse on me dit que l'adresse existe déjà. Et quand je redemande un mot de passe on me répond que l'adresse est introuvable. 
J'imagine que c'est la suppression du compte qui ne s'enregistre pas ? 

Par ailleurs j'ai crée un autre compte avec une autre adresse mais lorsque le lien de validation de l'adresse mail me renvoit vers le site il ne prend pas en compte mon inscription : je n'ai pas accès au fonctionnalités en écriture, impossible d'accéder à mon profil, ni de le modifier.

Merci de votre aide

**Comment by philippejadin** [comment]
bonjour, sur quel site êtes vous? Avec quel email ?

**Comment by Aureliensausy** [comment]
Bonjour,

L'adresse mail c'est celle avec laquelle je vous écris. Le site c'est agora
kit.
Je vous remercie.

Aurélien SAUSY
06 63 29 17 90
Mon site : questions de territoires
<http://aureliensausy.questionsdeterritoires.over-blog.com/>



Le mer. 29 janv. 2020 à 19:57, Philippe Jadin <notifications@github.com> a
écrit :

**Comment by philippejadin** [comment]
Bonjour,

Github ne transmet pas les adresses email, merci de me contacter directement à philippe (arobase) 123piano.com 

de cette façon je pourrai vous aider. Github est utilisé uniquement pour le développement de agorakit, pas pour le support utilisateur
