### ISSUE TITLE
Group notification emails arent going out

### ISSUE THREAD

**Issue by jalaen** [philippejadin/agorakit#284]
All the other email features are working. But daily/other interval emails of group activity arent being sent out. 

Is this working for everyone else?

**Comment by philippejadin** [comment]
Did you setup cron tasks? You need to run php artisan schedule:run at least
every few minutes (using cron, look in the laravel docs)


--
Philippe Jadin

**Comment by jalaen** [comment]
That's the one thing I didn't do. I'm sure that will resolve it. Thank you, closing.
