### ISSUE TITLE
Allow reply by mail

### ISSUE THREAD

**Issue by danielsum** [philippejadin/agorakit#4]
CF Loomio.

Pour ça on peut utiliser un Email reader que j'ai fait.

**Comment by philippejadin** [comment]
N'hésites pas  à implanter ça :-)
Je sais que mailgun propose une api pour recevoir des mails, l'avantage c'est qu'en réception, je crois que le nombre de mails reçu est illimité avec le plan gratuit

**Comment by danielsum** [comment]
Je regarde ça, sinon mon truc fonctionne avec n’importe quel type d’email compatible imap (y compris gmail simple :p).

Je peux tester ça et je te tiens au courant ;-)

-- 
Daniel Sum

On 24 novembre 2015 at 15:54:14, Phliippe Jadin (notifications@github.com) wrote:

N'hésites pas à implanter ça :-)
Je sais que mailgun propose une api pour recevoir des mails, l'avantage c'est qu'en réception, je crois que le nombre de mails reçu est illimité avec le plan gratuit

**Comment by philippejadin** [comment]
avec un imap c'est encore mieux :-)

Il faudrait essayer de filtrer mieux que loomio les mails, pour ne pas avoir plein de crasses quand quelqu'un répond. Et faire gaffe au spam...

**Comment by philippejadin** [comment]
There is now a reply button with autologin in notification email. Good enough so I'm closign this one
