### ISSUE TITLE
Better file and documents management

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/agorakit#41]
for document management 
[x] allow users to create folders
[x] allow users to put documents into those folders
[] Allow users to put links to external documents in the system

Technically
- tree implemented using simple additions to the file model
- new ui buttons
- added doc_type to the files table (0 = file / 1 = folder / 2 = link)

**Comment by philippejadin** [comment]
J'ai presque terminé l'intégration elfinder dans la branche filemanager https://github.com/philippejadin/Mobilizator/tree/filemanager 

il y a également une commande pour convertir l'ancien système vers des simples fichiers (plus besoin de la table files à terme)

**Comment by philippejadin** [comment]
elfinder installed and working on master branch.

Existing sites should use the php artisan mobilizator:convertfiles command in order to copy all the files from the previous flat, id based storageto the public folder. Once it is done, you can use your existing files with the new elfinder system.

**Comment by philippejadin** [comment]
Rolled back elfinder. The initial implementation was more flexible : allowed to mount various storage for groups including S3 or remote ftp. Kept authorship, and allowed to have private and public files and allow each owner to upload a new version of his/her file only (to be done).

**Comment by philippejadin** [comment]
Nicer file search (instant thanks to datatables)

**Comment by NicolasTOPLA** [comment]
Bonjour, nous utilisons Agorakit et nous aimerions pouvoir créer des dossiers pour ranger nos fichiers. Ca a l'air d'être possible mais je ne comprends pas comment faire. Pourriez-vous m'aider ?

**Comment by philippejadin** [comment]
J'ai enlevé cette fonctionalité qui embrouillait tout le monde. Mais si vous avez de bonne sidées au niveau intervface utilisateur, je suis preneur. L'expérience nous a montré que créer une hiérarchie de dossiers en groupe est un véritable casse-tête, on se retrouve avec ce genre de chose : 

pv/2018/monpv.doc
2017/pv et réunions/monpv.doc
réunios/2018/approuvé/mon pv.doc

je ne sais pas si vous voyez ce que je veux dire ?

**Comment by NicolasTOPLA** [comment]
Je comprends. Merci beaucoup pour votre réponse !

Le ven. 29 juin 2018 à 20:58, Philippe Jadin <notifications@github.com> a
écrit :
