### ISSUE TITLE
Better notification emails

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/agorakit#46]
- keep some formatting in the notifications's texts (or all?, same filtering as online)
- provide direct reply buttons and direct links to every comment
- do not summarize the discussion description
- provide simple links to be notified more often or less directly in the mails (single click opt-out)

**Comment by philippejadin** [comment]
Now with laravel 5.4 and nicer email templates, here is a guide to improve the mails : https://github.com/wildbit/postmark-templates

**Comment by msjmeyer** [comment]
Looking into it and will do some updates.

**Comment by philippejadin** [comment]
The recent commits add better email template thanks to laravel 5.4. Note that the templates use markdown if you want to work on it :-)
