### ISSUE TITLE
Add Open Street Maps as a map provider

### ISSUE THREAD

**Issue by bashrc** [philippejadin/agorakit#63]
This would be more free software friendly, and it might even be possible to cache maps on your local server. I like to avoid having Google encroach into everything.

**Comment by philippejadin** [comment]
Hello,
Thank you for your feedback. 

Currently the map is rendered using leaflet and open street map as map layer. So no Google in the process, yeah ! 

For the geocoding it is currently done with google (cfr.  https://github.com/philippejadin/agorakit/blob/master/config/geocoder.php ) which is a bit silly I agree. Geocoding is a one time thing (or to be more precise each time an address is filled somewhere), we only ask geocoder to convert an address to lon/lat without context. But still...

Do you know if geocoding can be done efficiently with open street map? I guess there is a provider for the geocoder lib I'm using.

**Comment by bashrc** [comment]
Ah that's better than I thought. I don't know is OSM can do that translation between addresses and coordinates. Perhaps. http://wiki.openstreetmap.org/wiki/Nominatim

**Comment by philippejadin** [comment]
In theory I could add 
OpenStreetMap::class => [],

in /config/geocoder.php

But it's not working well, so I'm closing this for now to reduce the queue. Please reopen if you have some idea on how to make it work better
