### ISSUE TITLE
Ability to delete users from admin panel

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#71]

**Comment by philippejadin** [comment]
This needs some thinking : what do we do with a deleted user's content?

Drupal has a nice way of doing this : http://cdn.inmotionhosting.com/support/images/stories/edu/Drupal_7/Structure/People/Cancel_Account/cancel-account2.png

We could do something simplier. At least separating the case of spam only account, and people with abusive behavior? Or people who ask all their content to be removed?

**Comment by msjmeyer** [comment]
I think that is a 2 part issue, lets say for test accounts that you know that is a test account you should be able to just delete the user. 

What if you create an additional panel where it shows the user, you suspend them and give you all the content and you can remove it or keep it. 

Yeah drupal has a nice way of doing this.

**Comment by philippejadin** [comment]
Problem is that the system needs a user for each content, else a lot of views will fail. If I delete a user, then suddenly all the references to that user_id won't work. I can cascade delete all the user's content, this is easy. 

But how to keep the content if I want? Assign it to someone else, not good imho

**Comment by msjmeyer** [comment]
Good point, I would say as a first step is to make it delete all user data.

For future, you could have something like a delete all data but transfer the group the user is admin or creator off to the admin user.

In most cases, if you delete the user, whether the user leaves or you ban the user. You don't care about the post, it's more the group that the user is the creator of.

**Comment by philippejadin** [comment]
agreed and in any case, everything is soft deleted so it's not that much a problem. I need to implement a trash recovery feature anyway :-)

**Comment by philippejadin** [comment]
Also user need to be able to cancel their own accounts
