### ISSUE TITLE
Image error on group page

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#74]
If you don't have an image set on a group and an image to group description with CKEditor you will get following error.

![image](https://user-images.githubusercontent.com/3487405/29541057-ba42a1ca-869f-11e7-8f87-bba5190b7740.png)

**Comment by philippejadin** [comment]
The thumbnail generation need refactoring. Curently a gray image is generated if there is no cover. It was a wrong idea in retrospect. Thanks for reminding

**Comment by philippejadin** [comment]
So technically : 
- create a ThumbnailController
- function like ThumbnailController@cover($model)
-> returns image url if there is a cover, false if not
-> $model can be group, user, file
