### ISSUE TITLE
Small spelling mistake 

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#75]
"Invite people who might be interessed by this group. Please don't spam people"

Should be 

"Invite people who might be interested in this group. Please don't spam people emails"
or 
"Invite people who might be interested in this group. 
Please don't spam people emails"

**Comment by philippejadin** [comment]
If you want to fix typos like that, and if you have the time, it would be highly appreciated that you make a pull request for that. In short : you fork the repository, then you edit the files in the ressources/lang/en directory. You do it directly inside github :-)

(Else I'll paste your fixes, but in the longer run it's easier for me if you can do the pull request system)

**Comment by philippejadin** [comment]
Hoho, but I see you already forked the repository. So if you want to work on this, the correct way to support multiple languages is to use the trans() function everywhere there is text that needs to be translated.

Everything explained much better here : https://laravel.com/docs/5.2/localization

**Comment by msjmeyer** [comment]
Yeah, I decided to help to work on your project since it's the perfect base platform for something I'm working on.

**Comment by philippejadin** [comment]
Great news! If it's close enough from this project, let's work together and merge your enhancements :-)
