### ISSUE TITLE
Make a preset image for Openshift.com

### ISSUE THREAD

**Issue by avamk** [philippejadin/agorakit#76]
Openshift.com has a [free of charge tier](https://www.openshift.com/pricing/index.html#) which might be very useful for citizen initiatives with limited funding. By providing a preset image (I think they are called "cartridges"?) of Agorakit, it will be easy for initiatives to deploy an instance right away.

**Comment by philippejadin** [comment]
Great idea! Would you have time to dig a bit how to do that? I'm also considering heroku but it's not clear if they provide mysql (although theoretically it could work with sqlite)
