### ISSUE TITLE
Getting logged out of account

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#77]
I noticed it logs you out of your accounts every few hours. 

Is this by design?

**Comment by philippejadin** [comment]
No,  and some others also mentioned this. It's strange because I use laravel built-in session handling.

According to this : https://github.com/laravel/framework/issues/2314 the db driver might be more stable. Weird, really... Need to dig deeper

**Comment by msjmeyer** [comment]
Yeah it is, im using RDS as a DB if that might help.

**Comment by msjmeyer** [comment]
This is the error in the logs im getting.
Illuminate\Session\TokenMismatchException in bootstrap/cache/compiled.php:3227

**Comment by philippejadin** [comment]
would this be the problem ?
https://stackoverflow.com/questions/30490821/laravel-5-tokenmismatchexception-on-php-5-6-9/30508294#30508294

I can say that on another install only a few users reported the problem.
Personnally I never experienced it with my user account. Which doesn't help
to debug unfortunately


Philippe Jadin

**Comment by msjmeyer** [comment]
Hmm I'm on php7.0, so far no one has reported it im just seeing it on my user.

**Comment by msjmeyer** [comment]
After digging a bit more this happens when you dont check remember me on the login page.
You log in and can just refresh a page and it will log you out.

**Comment by philippejadin** [comment]
Interesting, will dig
