### ISSUE TITLE
Cant get pins on map

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#78]
Hey, Im trying to get the map working. 

How do i get the pins on the map to work?

**Comment by philippejadin** [comment]
there are 3 ways : 
- on a user profile, the address field must be correctly filled (street, city, country)
- when you add an event you can set an address
- when you create or edit a group you can set an address

**Comment by msjmeyer** [comment]
Thanks, im trying and will let you know.

**Comment by msjmeyer** [comment]
I just tried, on your demo site it works, for me it gives.

4948 Concession 4 Rd, Lincoln, Canada
Your address cannot be geolocalized. Please use a simple format, like "number street, city"

Maybe im missing something.

**Comment by philippejadin** [comment]
is your server allowed to connect to google map (default geocoding provider?). If unsure, good luck, is tricky to debug :-)

**Comment by msjmeyer** [comment]
Im pretty sure it is allowed to connect, ill check.

**Comment by msjmeyer** [comment]
got it to work :)
Closing issue.
