### ISSUE TITLE
Duplicate tags

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#85]
When editing a group's tags it will duplicate tags.

For example, 
create group, tag1, tag2 
save
edit group add tag 3 
expected ( tag1 , tag2, tag3)
actual tag1, tag2, tag1, tag2, tag3

**Comment by philippejadin** [comment]
do you have the same problem with files?

**Comment by msjmeyer** [comment]
I haven't checked yet, ill check.

**Comment by msjmeyer** [comment]
File tags work as expected.
