### ISSUE TITLE
Feature request : user management (disabling, removing)

### ISSUE THREAD

**Issue by VMFnet** [philippejadin/agorakit#87]
It would be nice to have some basic user management : for instance, being able to disable temporarily a user account, or to remove one completely, with its content (e.g. a troll entering and spreading spam on Agorakit)

**Comment by philippejadin** [comment]
User deletion will soon land (it's very easy to add). 

Disabling user is a bit more tricky and needs more thinking. What would be the use case?

**Comment by VMFnet** [comment]
Sory for replying quite late, was AFK for a while.

the use case would be for instance when a user trolls or posts inapropriate content, it would be better for the admin or community manager to delete the account and all the associated contents.   

As for the option to disable an account, imagine you get someone who posts some content, but then, for some reason the community manager sees fit, this content doesn't match with the posting rules defined for the community. 
The admin or CM could then decide on a temporary ban (a few hours, a few days), like on forums / bulletin boards.

**Comment by philippejadin** [comment]
Agreed, looks like a good use case. I think I will change the user table to have a status for each user

0 : account created
1 : email verified
2 : user disabled
3 : user banned/deleted
4 : spam account

+ admin for it

Still need to find a good admin package to make it quicker to implement. Might just use datatables a bit more extensively, but I'm open, to suggestions.

**Comment by nedjo** [comment]
Good summary of potential user statuses. A hard question is what if anything happens to the user's content for each of these statuses.

Progress on this issue would also open the way to providing the ability to delete one's own account, which is key to users controlling their own data.

**Comment by philippejadin** [comment]
User content deletion has landed in master. With the choice for users (and admins) to delete all or assign to a new anonymous system user.

For banning users, I'd add a banned_until column to memberships (per group) table and the required policies updates.

**Comment by philippejadin** [comment]
membership level can now be freely edited by group admins
