### ISSUE TITLE
Allow user to change password

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/agorakit#89]
on the user edit form, add 2 password fields, if filled, password is changed

**Comment by msjmeyer** [comment]
I think the github account management has a really nice and clean way of doing this.
They way they separate the options are really good. 

I would say following something similar. 

<img width="505" alt="screen shot 2017-09-18 at 5 23 14 pm" src="https://user-images.githubusercontent.com/3487405/30570438-37802b74-9c96-11e7-9919-c6ca3f2f8c97.png">

**Comment by msjmeyer** [comment]
A really good feature to add is for the admin to force a password reset on a user or all users but that is a part of a different issue.

**Comment by philippejadin** [comment]
The forgot password feature allows somehow to change one's password, closing for now
