### ISSUE TITLE
Broken home page

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#93]
Hey, homepage is throwing an error after the latest updates.
Here is the gist for the error

https://gist.github.com/msjmeyer/b3cf0434a5c0f082c161b5d0a29f8a02

**Comment by philippejadin** [comment]
not so nice laravel upgrade bug I think. Relevant piece of the doc : 

Removing Compiled Services File
If it exists, you may delete the bootstrap/cache/compiled.php file. It is no longer used by the framework.

Flushing The Cache
After upgrading all packages, you should run php artisan view:clear to avoid Blade errors related to the removal of Illuminate\View\Factory::getFirstLoop(). In addition, you may need to run php artisan route:clear to flush the route cache.

from https://laravel.com/docs/5.4/upgrade

Try that and let me know

**Comment by msjmeyer** [comment]
I tried that and the issue was still there. 
So decided to just wipe and start from fresh on my test env and that worked.

I ran php artisan route:clear and php artisan config:cache and issue were still there. 
Nasty laravel upgrade bug :(

**Comment by philippejadin** [comment]
Did you find a way to correct the problem other than starting from scratch ?

By the way, things will be a bit unstable while the laravel 5.4 upgrade lands. Maybe I need to have a dev branch finally...

**Comment by msjmeyer** [comment]
I didn't look into it too much, it's easy enough to replicate. 
I would say a dev branch is a good idea 👍
