### ISSUE TITLE
Feature request: Address updates in user profile

### ISSUE THREAD

**Issue by msjmeyer** [philippejadin/agorakit#98]
Instead of the user guessing the format of the address.
Why not use something like this

Street:
Town:
Province:
Country:

For my use case, it would be wise for users not to give out there address since the info is public. 
Then simply not filling in the street it would just put pins in the middle of the town. Already tested and works

**Comment by philippejadin** [comment]
Good idea. Will implement it. But I'd like to keep the existing DB schema, so it won't work to edit existing adresses, is it a problem? (users will be able to provide a new address if they want to change/update it). Or I store it as json in the db...

**Comment by philippejadin** [comment]
Addresses should be 5 lines according to this : 
https://blink.ucsd.edu/facilities/services/mail/international/addressing/index.html

Would that work for you? It must work for every country...

**Comment by msjmeyer** [comment]
Agreed, keep the existing DB schema. 
If we use the 5 lines it will give users the option not to fill in the postal code and street and the map function will still work.

**Comment by msjmeyer** [comment]
Can also add the feature to hide/display each of the 5 lines on users edit page from the admin panel.
